### ISSUE TITLE
어플리케이션의 목적

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#12]
제목, 서론, 결론에 현재의 architecture를 통해 구현된 어플리케이션의 목적이 있었으면 좋겠습니다.
예를 들면 "이미지 분석하기", "이미지 분류를 통해 분석하기" 와 같은것이 있을수 있을것 같습니다.

**Comment by hijigoo** [comment]
다음 커밋으로 반영했습니다 https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/116d60ccd4965f4de43cdf2313a398da370233f1
검토 부탁드립니다. 좋은 리뷰 감사합니다!! 👍

**Comment by kyopark2014** [comment]
와우 빠른 반영 감사드려요
