### ISSUE TITLE
train.py에 대한 코드 설명

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#13]
train.py의 코드에 대한 설명이 없습니다.
train.py를 다른 repo에서 받은것이라면 link를 달아야 할것 같은데요.
다른데서 다운 받았더라도 수정한 부분이 있다면 설명해주면 좋을것 같습니다.

**Comment by hijigoo** [comment]
직접 작성한 파일이여서 다음 커밋으로 추가 설명을 넣었습니다 😄 
https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/5040372d5d5c0b8bbf75ed3990fdaf123f088710
