### ISSUE TITLE
데이터 다운로드

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#14]
[Amazon SagemMaker Pipeline을 이용한 모델 학습 및 배포 자동화](https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice#amazon-sagemmaker-pipeline%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%AA%A8%EB%8D%B8-%ED%95%99%EC%8A%B5-%EB%B0%8F-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94)를 보면 kaggle에서 데이터를 다운로드 하여 일부만 사용하고 있습니다.
다운로드 과정이 복잡한데, github repo에 사용하는 데이터셋을 올리면 어떻까합니다.

**Comment by hijigoo** [comment]
/datasets 경로에 실제로 사용하는 파일을 올리고 README 도 업데이트 했습니다.!  💯 
README 업데이트 내용입니다. https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/f806fce24cfd8298e2acec3fdee44d78953aef62
