### ISSUE TITLE
코드 다운로드와 업로드 과정

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#15]
아래와 같이 train.py, flower.py, build-pipeline-train.ipynb등을 다운로드후에 SageMaker Studio로 업로드하라고 가이드하고 있는데요. 아래처럼 studio에서 clone해서 한꺼번에 다운로드 해서 쓰면 편할것 같습니다. 검토한번 부탁해요.

git clone https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice

다음으로 학습 단계에 필요한 코드를 다운받고 SageMaker Studio 에 업로드합니다. 먼저 SageMaker Studio에서 접속해서 왼쪽 메뉴에서 폴더 아이콘을 클릭한 뒤 src 폴더를 생성합니다. 그리고 [train.py](https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/blob/main/ml/src/train.py) 과 [flower.py](https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/blob/main/ml/src/flowers.py) 파일을 다운 받아서 /src/train.py 경로와 src/train.py 경로에 각각 업로드 합니다.

이제 앞서 올린 train.py을 이용해서 학습 단계를 생성하고 학습 단계만 있는 파이프라인을 구성합니다. 이를 위해서 [build-pipeline-train.ipynb](https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/blob/main/ml/build-pipeline-train.ipynb)을 다운 받고 SageMaker Studio에서 루트 폴더로 나와서 /build-pipelin-train.ipynb 경로로 업로드 합니다.

**Comment by hijigoo** [comment]
Sample Project 단계를 추가하고 전체 설명을 변경했습니다. 사용자가 훨씬 이해하기 편하진 것 같네요 👍  
아래 두 Commit 으로 반영했습니다. 감사합니다!
https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/e2618ae1413741bdd17825b09708cb94ad0c838c
https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/453616674ed874653a85b2eb79c21588766c3845
