### ISSUE TITLE
architecture의 subnet 관련

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#4]
vpc에서 subnet 생성시 public subnet 2, private subnet 2개를 만들도록 하는데 architecture는 public 1, private 1개로 표시되고 있습니다. 
멀티 az를 doc에서 설명하거나 그림에 모두 표시하거나 하는것이 이해에 도움이 될것 같아 보입니다.

**Comment by hijigoo** [comment]
넵넵! 그림에 넣으면 너무 복잡해 보일 것 같아서 내용에 추가했습니다
