### ISSUE TITLE
WEB 로그 보려면 어떻게 해야할까요?

### ISSUE THREAD

**Issue by kyopark2014** [hijigoo/ecs-fargate-sagemaker-based-webservice#9]
cdk로 deploy후에 was 연결 확인을 위하여 크롬에서 /was/heathy로 접속하였는데 504 에러가 나고 있습니다.
관련 로그를 WEB에서 확인하려고 보니 아래와 같은 로그만 나오는데요, request / response의 내용을 로그로 확인할 수 있도록 app에서 로그를 남길수 있으면 좋겠습니다. 

- 접속 URL
http://app-web-alb-702844279.ap-northeast-2.elb.amazonaws.com/was/health/

- WEB 로그
ECS에 WEB service task의 로그가 아래와 같습니다.

----------------------------------------------------------
|                        message                         |
|--------------------------------------------------------|
| [33m[nodemon] 2.0.22[39m                             |
| [33m[nodemon] to restart at any time, enter `rs`[39m |
| [33m[nodemon] watching path(s): *.*[39m              |
| [33m[nodemon] watching extensions: js,mjs,json[39m   |
| [32m[nodemon] starting `node app.js`[39m             |
| Example app listening on port 8000!                    |
----------------------------------------------------------

**Comment by kyopark2014** [comment]
추가로그를 보면 무언가 에러는 나는데 원인을 모르겠습니다. 로그가 좀 나오면 좋겠습니다. 

---------------------------------------------------------------------------------
|                                    message                                    |
|-------------------------------------------------------------------------------|
| [33m[nodemon] 2.0.22[39m                                                    |
| [33m[nodemon] to restart at any time, enter `rs`[39m                        |
| [33m[nodemon] watching path(s): *.*[39m                                     |
| [33m[nodemon] watching extensions: js,mjs,json[39m                          |
| [32m[nodemon] starting `node app.js`[39m                                    |
| Example app listening on port 8000!                                           |
| undefined                                                                     |
| undefined:1                                                                   |
| undefined                                                                     |
| ^                                                                             |
| SyntaxError: Unexpected token u in JSON at position 0                         |
|     at JSON.parse (<anonymous>)                                               |
|     at Request._callback (/app/router.js:35:40)                               |
|     at self.callback (/node_modules/request/request.js:185:22)                |
|     at Request.emit (node:events:513:28)                                      |
|     at Request.onRequestError (/node_modules/request/request.js:877:8)        |
|     at ClientRequest.emit (node:events:513:28)                                |
|     at Socket.socketErrorListener (node:_http_client:502:9)                   |
|     at Socket.emit (node:events:513:28)                                       |
|     at emitErrorNT (node:internal/streams/destroy:151:8)                      |
|     at emitErrorCloseNT (node:internal/streams/destroy:116:3)                 |
| Node.js v18.16.0                                                              |
| [31m[nodemon] app crashed - waiting for file changes before starting...[39m |
---------------------------------------------------------------------------------

**Comment by hijigoo** [comment]
> 504 에러는 router.js의 경로를 수정하지 않아서 발생하였고, 경로 수정후에 아래처럼 동작하였습니다.
> 
> message
> �[33m[nodemon] 2.0.22�[39m
> �[33m[nodemon] to restart at any time, enter `rs`�[39m
> �[33m[nodemon] watching path(s): *.*�[39m
> �[33m[nodemon] watching extensions: js,mjs,json�[39m
> �[32m[nodemon] starting `node app.js`�[39m
> Example app listening on port 8000!
> {"message":"WAS-Connected"}
> 로그가 좀 나오면 좋기는 한데, 너무 많은 수정이 필요하다면 현상태 유지하여도 될것 같습니다.

다음 Commit 으로 반영했습니다. 좋은 리뷰 감사합니다!
https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/commit/3dafd240437d766072cd5b57996fe77b25668882

Timeout이 발생하면 아래와 같이 응답과 로그가 나오도록 수정했습니다.
<img width="608" alt="image" src="https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/assets/1788481/5383ad69-b575-4d99-8660-fd14214ef866">

<img width="519" alt="image" src="https://github.com/hijigoo/ecs-fargate-sagemaker-based-webservice/assets/1788481/e8faeaac-7114-4d60-ba9b-befac7c5252f">
